export {default as HeaderMain} from "./Header/Header.jsx"
export {default as HeaderLogin} from "./Login/HeaderLogin.jsx"
export {default as Login} from "./Login/Login.jsx"
export {default as Footer} from "./footer/Footer.jsx"
export {default as MainSection} from "./MainSection/MainSection.jsx"